App\MicroAdmin:
    pilets:
        - name: 'piral_module_form'
          version: 1
          link: '/_resources/piral-module-form/dist/index.js'
          requireRef: System.import
          spec: v2
